name: Snyk CI Test

on:
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Verify Snyk
        run: snyk --version

      - name: Run Snyk Code
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
